language: python

python:
  - 3.4
  - 3.5
  - 3.6

cache: pip

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install virtualenv
  - pip install tox-travis

script:
  - tox

after_success:
  - pip install codecov && codecov

notifications:
  email: false
